<?php

namespace Trez\LogicielTrezBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeclarationTvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeclarationTvaRepository extends EntityRepository
{
    public function getLast()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('d')
            ->from('TrezLogicielTrezBundle:DeclarationTva', 'd')
            ->orderBy('d.date', 'DESC')
            ->setFirstResult(0)
            ->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function findByDateDesc()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('d')
            ->from('TrezLogicielTrezBundle:DeclarationTva', 'd')
            ->orderBy('d.date', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
