<?php

namespace Trez\LogicielTrezBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExerciceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciceRepository extends EntityRepository
{
    public function getLastFactureNumero($exercice_id, $type_facture_id)
    {
        $em = $this->getEntityManager();
        $dql =  'SELECT f.numero FROM TrezLogicielTrezBundle:Facture f '
            .'JOIN f.ligne l '
            .'JOIN l.sousCategorie s '
            .'JOIN s.categorie c '
            .'JOIN c.budget b '
            .'JOIN b.exercice e '
            .'JOIN f.typeFacture t '
            .'WHERE e.id = ?1 AND t.id = ?2 '
            .'ORDER BY f.numero DESC';

        $query = $em->createQuery($dql);
        $query->setParameters(array(1 => $exercice_id, 2 => $type_facture_id));

        $result = $query->getScalarResult();
        $result[]['numero'] = '0';

        return $result;
    }

    public function getAllowed($user_id)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('e')
            ->from('TrezLogicielTrezBundle:Exercice', 'e')
            ->leftJoin('e.budgets', 'b')
            ->leftJoin('b.categories', 'c')
            ->leftJoin('c.sousCategories', 's')
            ->leftJoin('s.lignes', 'l')
            ->leftJoin('l.users', 'u')
            ->where('u.id = ?1')
            ->setParameters(array(1 => $user_id));

        return $qb->getQuery()->getResult();
    }
}
