<?php

namespace Trez\LogicielTrezBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends EntityRepository
{
    public function getUndeclaredBeforeDate(\DateTime $date)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('f')
            ->from('TrezLogicielTrezBundle:Facture', 'f')
            ->where('f.declarationTva IS NULL')
            ->andWhere('f.date <= ?1')
            ->orderBy('f.date', 'ASC')
            ->setParameters(array(1 => $date));

        return $qb->getQuery()->getResult();
    }
}
