<?php

namespace Trez\LogicielTrezBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LigneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneRepository extends EntityRepository
{
    public function getLastCle($sous_categorie_id)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('l.cle')
            ->from('TrezLogicielTrezBundle:Ligne', 'l')
            ->innerJoin('l.sousCategorie', 'c')
            ->where('c.id = ?1')
            ->orderBy('l.cle', 'DESC')
            ->setFirstResult(0)
            ->setMaxResults(1)
            ->setParameters(array(1 => $sous_categorie_id));

        $result = $qb->getQuery()->getResult();
        $result[]['cle'] = 0;

        return $result;
    }

    public function getAllowed($sousCategorie_id, $user_id)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('l')
            ->from('TrezLogicielTrezBundle:Ligne', 'l')
            ->leftJoin('l.sousCategorie', 's')
            ->leftJoin('l.users', 'u')
            ->where('s.id = ?1')
            ->andWhere('u.id = ?2')
            ->orderBy('l.cle', 'ASC')
            ->setParameters(array(1 => $sousCategorie_id, 2 => $user_id));

        return $qb->getQuery()->getResult();
    }
}
