<?php

namespace Trez\LogicielTrezBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SousCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousCategorieRepository extends EntityRepository
{
    public function getAll($categorie_id)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select(['s', 'SUM(l.debit) AS debit', 'SUM(l.credit) AS credit'])
            ->from('TrezLogicielTrezBundle:sousCategorie', 's')
            ->leftJoin('s.lignes', 'l')
            ->innerJoin('s.categorie', 'c')
            ->where('c.id = ?1')
            ->groupBy('s.id')
            ->orderBy('s.cle', 'ASC');

        $query = $qb->getQuery();
        $query->setParameters([1 => $categorie_id]);

        return $query->getResult();
    }
}
