parameters:
#    trez_logiciel_trez.example.class: Trez\LogicielTrezBundle\Example

services:
#    trez_logiciel_trez.example:
#        class: %trez_logiciel_trez.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    twig.extension.evaluate:
        class: Trez\LogicielTrezBundle\Twig\Extension\EvaluateExtension
        tags:
            - { name: twig.extension }
    twig.extension.excel_format:
        class: Trez\LogicielTrezBundle\Twig\Extension\ExcelExtension
        tags:
            - { name: twig.extension }
        arguments: [ @doctrine.orm.entity_manager ]
    trez.logiciel_trez.openid_user_manager:
        class: Trez\LogicielTrezBundle\Model\OpenIdUserManager
        arguments: [ @fp_openid.identity_manager, @doctrine.orm.entity_manager ]
    validator.unique.numero_unique:
        class: Trez\LogicielTrezBundle\Validator\Constraints\NumeroUniqueValidator
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: validator.constraint_validator, alias: numero_unique_service }
    trez.logiciel_trez.acl_proxy_factory:
        class: Trez\LogicielTrezBundle\Service\AclProxy\AclProxyFactory
        arguments: [ @security.context, @doctrine.orm.entity_manager ]
    trez.logiciel_trez.breadcrumbs:
        class: Trez\LogicielTrezBundle\Service\BreadcrumbsService
        arguments: [ @doctrine.orm.entity_manager, @router, @white_october_breadcrumbs ]
    trez.controller.exception:
        class: Trez\LogicielTrez\Controller\ExceptionController
        arguments:
            - @twig
            - %kernel.debug%
